### ISSUE TITLE
Symlink Setup Issue for BUILD 2019 demo

### ISSUE THREAD

**Issue by woojinko** [microsoft/MixedReality-SpectatorView#189]
Hi everyone! I'm really excited to be working with Spectator View. It looks like it would be the perfect tool to visualize a HoloLens project I'm working on.  I'm currently working on a Mac with Unity 2018.3.14f1 in order to get the iOS setup working with my iPhone.

I followed the setup instructions, but I ran into some errors when trying to work with and set up the BUILD 2019 demo.

Steps I took:
1. Finished all the way up to (inclusive) "Setting up the master branch" section in the /master/README.md with running "run 'sh tools/scripts/SetupRepository.sh'". I considered using the release/1.0.0-beta branch, but running "sh tools/scripts/SetupRepository.sh" resulted in this error:
<img width="820" alt="Screen Shot 2019-08-17 at 6 36 12 PM" src="https://user-images.githubusercontent.com/35548021/63219028-e9aaad80-c11d-11e9-98ec-777f15202f57.png">
So I decided just to work with master.
2. I wanted to continue to the "Adding references to your own project" section because I ultimately want to be using spectator view for my own project, but the instructions included running "tools\Scripts\AddDependencies.bat "Assets" "sv"", which I can't run on a Mac. I searched the scripts folder for a AddDependencies.sh, but couldn't find one, only .bat and .ps1 files. I'm not well learned in this area, so please let me know if there's a way to run sh or ps1 files on my Mac!
3. So, I decided to just try out a sample first. I followed the instructions on /master/samples/Build2019Demo.Unity/README.md, but upon completing steps 1-3, I ran into a bunch of errors. 
<img width="1398" alt="Screen Shot 2019-08-17 at 6 28 20 PM" src="https://user-images.githubusercontent.com/35548021/63219077-072c4700-c11f-11e9-8ecd-22fd63a824df.png">
<img width="1404" alt="Screen Shot 2019-08-17 at 6 28 27 PM" src="https://user-images.githubusercontent.com/35548021/63219076-072c4700-c11f-11e9-9356-b9984600e311.png">
I noticed that there were some common errors between this and https://github.com/microsoft/MixedReality-SpectatorView/issues/135, so I read through the thread and saw that at the end chrisfromwork wrote:
<img width="724" alt="Screen Shot 2019-08-17 at 6 45 18 PM" src="https://user-images.githubusercontent.com/35548021/63219083-45296b00-c11f-11e9-9368-b94803969a2a.png">
I checked the scripts again but couldn't find a FixSymbolicLinkedDirectories.sh, only .bat and .ps1.

Could I get some help on resolving some of these errors? And will this pull request https://github.com/microsoft/MixedReality-SpectatorView/pull/188 help with this?

Sorry for asking so many questions, but lastly, my project right now is using HTK and Unity 2017.4.30f1 since I drew a lot from the Microsoft Mixed Reality tutorials for Hololens 1 that used these dependencies. I noticed that this Spectator View repo requires Unity 2018.3.14f1 and I'm assuming some MRTK instead of HTK dependencies. Would there be a way to still use Spectator View with my project? Or would I have to pipe all the HTK dependent parts of my project to MRTK and Unity 2018?

Thank you!

**Comment by chrisfromwork** [comment]
I have a pull request out here that addresses some problems that we were seeing building the samples solution on mac: https://github.com/microsoft/MixedReality-SpectatorView/pull/188

There are a few problems that we observed for the Build 2019 project:
1) Some scripts were renamed in the MRTK causing breaks in the scene. This is fixed in the pull request.
2) Symbolic linked directories that resolved on PCs did not resolve on macs. We shortened paths to fix this in the pull request.
FWIW - it also looks like you need to install text mesh pro. The Build 2019 project enables text mesh pro synchronization by default.

For setting up your own project on a mac, if you aren't using the MRTK, its unlikely that youll hit most of the issues observed in the Build 2019 project. If you look at how the SpectatorView.Example.Unity project is setup. You can add symbolic links to your assets folder in a similar manner: https://github.com/microsoft/MixedReality-SpectatorView/tree/master/samples/SpectatorView.Example.Unity/Assets
For building iOS, you will want to run SetupRepository.sh to obtain external dependencies (The pull request described above now obtains the ARKit Unity Plugin zip file and extracts it to the external/ARKit-Unity-Plugin directory). You can then set up symbolic links with commands similar to the following when in your project assets folder:
ln -sfn ../../../../external/ARKit-Unity-Plugin ARKit-Unity-Plugin 


There has been an assumption that building a spectator view experience would require a PC. Are you able to build and deploy a HoloLens solution on a mac? We can invest more in sh scripts as needed, but we had felt that the powershell and bat scripts would get most consumers unblocked.

**Comment by woojinko** [comment]
Thank you so much for the in-depth reply! I'll try it out soon with your pull request and suggestions for setting up symbolic links as well.

To answer the last part, I have not yet tried to build and deploy a Hololens solution on a Mac. I have been building and deploying my current project on PC with unity and visual studio. However, since I have an iPhone rather than an Android device, I thought that the only way to utilize spectator view for iOS would be to move the whole project to my Mac and then build it with spectator view setup there. 

Am I misunderstanding how the work flow should be done in order to enable my iPhone to view the Hololens experience of my project? Is there a way to instead build and deploy my project on to Hololens via PC first, and then separately deploy my project with spectator view set up via Mac immediately afterwards?

**Comment by chrisfromwork** [comment]
No, you won't be able to build an iOS application on a PC. But if you setup symbolic links/spectator view dependencies for your project on a PC and then reclone that project on the mac things should work.

FWIW - the standalone iOS experience won't be very compelling when not observing a user wearing a HoloLens. The HoloLens needs to broadcast content for the iOS device to display anything. Also, you need to setup an assets cache for your application that is shared across devices. This needs to be configured on one development machine and then shared with the other development machine. Asset caches aren't currently created in a deterministic manner, so recreating them on different development machines will break the spectator view experience.

**Comment by chrisfromwork** [comment]
I am going to close this issue for now based on a lack of activity. Please feel free to reopen this issue if you are still experiencing issues.
