### ISSUE TITLE
Unity Version Requirement / HoloToolKit Compatibility 

### ISSUE THREAD

**Issue by woojinko** [microsoft/MixedReality-SpectatorView#209]
Hi again,

Thank you for all the help on the last issue I opened a few weeks ago. I decided to work with PC/android rather than Mac/iOS and was able to get the BUILD2019 sample scene working on an android device!

Like I mentioned in the last issue, my goal is to incorporate spectator view into a project I've been working on that uses Unity 2017.4.30f1 and HoloToolKit 2017 as it follows Microsoft's MR tutorial for the Hololens 1.

Before I move forward in trying to combine spectator view with my project, I was wondering if I could receive some clarification on a few things to save me some time.

1. Does SpectatorView still work with older Unity versions like 2017.4.30f1? If so, would there be any differences in the set up steps?
2. Does SpectatorView work with HoloToolKit or is it specifically meant only for MixedRealityToolKit use?

Thank you,
Woojin

**Comment by chrisfromwork** [comment]
FWIW - we don't have intentions of formally supporting Unity 2017.*

We have seen some issues with TextMeshPro for Unity 2017.* I know that TextMeshPro packages changed between Unity 2017.* and Unity 2018.*, which causes some errors when attempting to reference the TextMeshPro dll's via the Spectator View asmdef. You will need to remove this reference if you are using Spectator View in Unity 2017.*. If you aren't using TextMeshPro, removing this reference likely won't make a difference. Synchronizing TextMeshPro requires adding a preprocessor directive to the player settings, which isn't enabled by default.

There may be additional issues using Unity 2017.* for ARCore, ARKit, Azure Spatial Anchors or other external dependencies. I do not know if anyone has attempted building Spectator View for older Unity versions/what runtime errors they have encountered.

SpectatorView doesn't have any dependencies on HoloToolKit or MixedRealityToolkit. You should theoretically be able to use SpectatorView with either codebases if things compile in your chosen Unity version. There may be different issues with shaders/components not compiling for Android/iOS. I think many of the shaders have been fixed for cross-platform compatilibility in the MixedRealityToolkit-Unity project. I do not know if these items have been fixed for HoloToolKit.

Note: I am going to close this issue because there isn't any associated development task. Feel free to keep asking questions.
