### ISSUE TITLE
Android连接Hololens显示问题

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/MixedReality-SpectatorView#210]
我把我的项目与SpectatorView结合起来。我把 UI、模型 两个的父物体都放在一个空物体下，然后给这个空物体【GameObjectHierarchyBroadcaster】脚本。但是当我连接成功用手机观看时，UI 以白色片显示，模型都不显示（是否是我的模型上存在透明材质的原因）。你能告诉我模型和UI显示正确的设置方法吗？

**Comment by chrisfromwork** [comment]
Original Question:
I combined my project with the SpectatorView. I put both the parent object of the UI and the model under an empty object, and then give the empty object [GameObjectHierarchyBroadcaster] script. But when I connect successfully with my mobile phone, the UI is displayed in white and the model is not displayed (whether it is the reason for the transparent material on my model). Can you tell me how the model and UI display the correct settings?

Answer:
I think you are encountering an issue with windows assets not working correctly on Android. We have seen a variety of issues where transparent rendering does not work on Android when using our state synchronization loci. What shader are you using for this transparent material? You may also be seeing this issue if you are using the Unity standard shader: https://github.com/microsoft/MixedReality-SpectatorView/issues/176. Do you know whether your shader renders transparent content correctly on android? If it does render correctly, its likely an issue with how the state synchronization logic hands around properties through the MaterialPropertyAsset/MaterialPropertyAssetCache/MaterialsBroadcaster and you may need to write custom logic. If it doesn't render correctly, you may need to fix your shader/change your rendering behavior so that your material is compatible with Android.

我认为您遇到的问题是Windows资产在Android上无法正常运行。 我们已经看到了在使用我们的状态同步轨迹时透明渲染在Android上不起作用的各种问题。 你使用什么着色器来制作这种透明材料？ 如果您使用的是Unity标准着色器，则可能还会看到此问题：https：//github.com/microsoft/MixedReality-SpectatorView/issues/176。 你知道你的着色器是否在android上正确呈现透明内容？ 如果它确实正确渲染，它可能是状态同步逻辑如何通过MaterialPropertyAsset / MaterialPropertyAssetCache / MaterialsBroadcaster处理属性的问题，您可能需要编写自定义逻辑。 如果无法正确渲染，您可能需要修复着色器/更改渲染行为，以使您的材质与Android兼容。

**Comment by RenSiyao** [comment]
> 原始问题：
> 我将我的项目与SpectatorView结合起来。我将UI的父对象和模型放在一个空对象下，然后给出空对象[GameObjectHierarchyBroadcaster]脚本。但是当我用我的手机成功连接时，UI显示为白色并且不显示模型（这是否是我模型上透明材料的原因）。你能告诉我模型和UI如何显示正确的设置吗？
> 
> 答：
> 我认为您遇到的问题是Windows资产在Android上无法正常运行。我们已经看到了在使用我们的状态同步轨迹时透明渲染在Android上不起作用的各种问题。你使用什么着色器来制作这种透明材料？如果您使用Unity标准着色器，您可能也会看到此问题：[＃176](https://github.com/microsoft/MixedReality-SpectatorView/issues/176)。你知道你的着色器是否在android上正确呈现透明内容？如果它确实正确渲染，它可能是状态同步逻辑如何通过MaterialPropertyAsset / MaterialPropertyAssetCache / MaterialsBroadcaster处理属性的问题，您可能需要编写自定义逻辑。如果无法正确渲染，您可能需要修复着色器/更改渲染行为，以使您的材质与Android兼容。
> 
> 我认为您遇到的问题是Windows资产在Android上无法正常运行。我们已经看到了在使用我们的状态同步轨迹时透明呈染在Android上不起作用的各种问题。你使用什么着色器来制作这种透明材料？如果您使用的是Unity标准着色器，则可能还会看到此问题：https：//github.com/ [/ issues / 176。](https://github.com/microsoft/MixedReality-SpectatorView/issues/176)你知道你的着色器是否在android上正确呈现透明内容？如果它确实正确渲染，它可能是状态同步逻辑如何通过MaterialPropertyAsset / MaterialPropertyAssetCache / MaterialsBroadcaster处理属性的问题，您可能需要编写自定义逻辑。如果无法正确渲染，您可能需要修复着色器/更改革行行为，以使您的材质与Android的兼容。
感谢您的回复。
也就是说会有一些特殊的材质球在Android不能显示，需要使用Android能接受的材质才可以正常显示是吗？

**Comment by chrisfromwork** [comment]
I apologize for the delay. Yes android usable materials should display correctly. 
我为延误道歉。是 安卓可用材料应正确显示。

We're going to close this issue for now. Please reopen this issue if you hit additional problems.
我们现在要结束这个问题。如果遇到其他问题，请重新打开此问题。
