### ISSUE TITLE
Unity Plugin

### ISSUE THREAD

**Issue by Dustin-Boyle** [microsoft/MixedReality-SpectatorView#321]
Can you please create a unity package for SpectatorView for us Unity Developers? I'm sure a lot more devs would utilize this feature if you did.

**Comment by chrisfromwork** [comment]
We are looking into this now. Our master branch does have functionality for creating a unity package that can be shared amongst teams. We are still working through how to consume dependencies such as Azure Spatial Anchors, QR Code Detection dlls and the MRTK, which will delay having a NPM feed.

I am going to plan on tracking the issue here: https://github.com/microsoft/MixedReality-SpectatorView/issues/268#issuecomment-607441498

**Comment by chrisfromwork** [comment]
Please reopen this issue if the other issue doesn't suffice.

**Comment by InitusJames** [comment]
Any progress on this plugin? I've been at this setup instructions for a few days on and off, it's not as simple as ABC, there seems to be steps that are just enough unclear to make mistakes with the setup. I am struggling to build the unity package properly, very frustrating. :(
